export const FETCH_SUPPORT_LIST_PENDING = 'FETCH_SUPPORT_LIST_PENDING';
export const FETCH_SUPPORT_LIST_FULFILLED = 'FETCH_SUPPORT_LIST_FULFILLED';
export const FETCH_SUPPORT_LIST_REJECTED = 'FETCH_SUPPORT_LIST_REJECTED';