export const FETCH_DEMAND_LIST_PENDING = 'FETCH_DEMAND_LIST_PENDING';
export const FETCH_DEMAND_LIST_FULFILLED = 'FETCH_DEMAND_LIST_FULFILLED';
export const FETCH_DEMAND_LIST_REJECTED = 'FETCH_DEMAND_LIST_REJECTED';