export const USER_LOGIN_PENDING = 'USER_LOGIN_PENDING' ;
export const USER_LOGIN_FULFILLED = 'USER_LOGIN_FULFILLED' ;
export const USER_LOGIN_REJECTED = 'USER_LOGIN_REJECTED' ;

export const USER_LOG_OUT_PENDING = 'USER_LOG_OUT_PENDING';
export const USER_LOG_OUT_FULFILLED = 'USER_LOG_OUT_FULFILLED';
export const USER_LOG_OUT_REJECTED = 'USER_LOG_OUT_REJECTED';

export const USER_LOGGED_IN_PENDING = 'USER_LOGGED_IN_PENDING';
export const USER_LOGGED_IN_FULFILLED = 'USER_LOGGED_IN_FULFILLED';

