export const FETCH_TRANSFER_LIST_PENDING = 'FETCH_TRANSFER_LIST_PENDING';
export const FETCH_TRANSFER_LIST_FULFILLED = 'FETCH_TRANSFER_LIST_FULFILLED';
export const FETCH_TRANSFER_LIST_REJECTED = 'FETCH_TRANSFER_LIST_REJECTED';

export const CREATE_TRANSFER_ORDER_PENDING = 'CREATE_TRANSFER_ORDER_PENDING';
export const CREATE_TRANSFER_ORDER_FULFILLED = 'CREATE_TRANSFER_ORDER_FULFILLED';
export const CREATE_TRANSFER_ORDER_REJECTED = 'CREATE_TRANSFER_ORDER_REJECTED';

export const UPDATE_TRANSFER_ORDER_PENDING = 'UPDATE_TRANSFER_ORDER_PENDING';
export const UPDATE_TRANSFER_ORDER_FULFILLED = 'UPDATE_TRANSFER_ORDER_FULFILLED';
export const UPDATE_TRANSFER_ORDER_REJECTED = 'UPDATE_TRANSFER_ORDER_REJECTED';