export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING';
export const FETCH_USERS_FULFILLED = 'FETCH_USERS_FULFILLED';
export const FETCH_USERS_REJECTED = 'FETCH_USERS_REJECTED';

export const FETCH_OPERATORS_PENDING = 'FETCH_OPERATORS_PENDING';
export const FETCH_OPERATORS_FULFILLED = 'FETCH_OPERATORS_FULFILLED';
export const FETCH_OPERATORS_REJECTED = 'FETCH_OPERATORS_REJECTED';


export const FETCH_USER_ROLES_PENDING = 'FETCH_USER_ROLES_PENDING';
export const FETCH_USER_ROLES_FULFILLED = 'FETCH_USER_ROLES_FULFILLED';
export const FETCH_USER_ROLES_REJECTED = 'FETCH_USER_ROLES_REJECTED';


export const SAVE_USER_PENDING = 'SAVE_USER_PENDING';
export const SAVE_USER_FULFILLED = 'SAVE_USER_FULFILLED';
export const SAVE_USER_REJECTED = 'SAVE_USER_REJECTED';



export const DELETE_USER_PENDING = 'DELETE_USER_PENDING';
export const DELETE_USER_FULFILLED = 'DELETE_USER_FULFILLED';
export const DELETE_USER_REJECTED = 'DELETE_USER_REJECTED';